server:
   port: 8443
   ssl:
      enabled: true
      key-store: classpath:com.ecfghjp.com.p12
      key-store-type: pkcs12
      key-alias: selfsigned_localhost_sslserver
      key-store-password: himAchAl@123

spring:
   application:
      name: TRAINING-SERVICE
   mvc:
      throw-exception-if-no-handler-found: true
   resources:
      add-mappings: false
   zipkin:
      base-url: http://127.0.0.1:9411/
      
      
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
         defaultZone: http://localhost:8761/eureka/
   instance:
      hostname: localhost

         

